[package]
name = "spike-render"
version = "0.1.0"
edition = "2021"

[lib]
name = "fable_render"
crate-type = ["cdylib", "rlib"]

[build-dependencies]
cc = "1"

[dependencies]
fontdue = "0.9"
jni = "0.22.4"
log = "0.4"
png = "0.18"
rustybuzz = "0.20.1"
wgpu = { version = "30.0.0", default-features = false, features = ["std", "vulkan", "wgsl", "parking_lot"] }
pollster = "0.4"

[profile.dev]
opt-level = 1
